{
 "title": "kodo-rspub",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ns",
    "query": "label_values(kodo_rspub_auto_sessionpool_stat{}, namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(kodo_rspub_auto_sessionpool_stat{namespace=\"$ns\"},pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Get Session Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kodo_rspub_session_get_stat_count{namespace=\"$ns\",pod=\"$pod\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Get Session QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kodo_rspub_session_rate_count{namespace=\"$ns\",pod=\"$pod\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Session Pool Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kodo_rspub_auto_sessionpool_stat{namespace=\"$ns\",pod=\"$pod\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Session Limiter Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kodo_rspub_auto_sessionpool_limit_stat{namespace=\"$ns\",pod=\"$pod\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Get Session Request Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kodo_rspub_auto_sessionpool_counter_stat{namespace=\"$ns\",pod=\"$pod\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RS Refresh Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kodo_rspub_session_refresh_error_count{namespace=\"$ns\",pod=\"$pod\"}[1m])",
     "legendFormat": "{{service}}|{{error}}"
    }
   ]
  },
  {
   "title": "Wait Session  Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(kodo_rspub_rs_mongo_requests_wait_session_bucket{pod=\"$pod\",namespace=\"$ns\",op=\"wait_session\"}[2m])))",
     "legendFormat": "99值"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(kodo_rspub_rs_mongo_requests_wait_session_bucket{pod=\"$pod\",namespace=\"$ns\",op=\"wait_session\"}[2m])))",
     "legendFormat": "95值"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(kodo_rspub_rs_mongo_requests_wait_session_bucket{pod=\"$pod\",namespace=\"$ns\",op=\"wait_session\"}[2m])))",
     "legendFormat": "50值"
    },
    {
     "expr": "histogram_quantile(0.999, sum by(le) (rate(kodo_rspub_rs_mongo_requests_wait_session_bucket{pod=\"$pod\",namespace=\"$ns\",op=\"wait_session\"}[2m])))",
     "legendFormat": "99.9值"
    },
    {
     "expr": "sum(rate(kodo_rspub_rs_mongo_requests_wait_session_sum{pod=\"$pod\",namespace=\"$ns\",op=\"wait_session\"}[2m])) / sum(rate(kodo_rspub_rs_mongo_requests_wait_session_count{pod=\"$pod\",namespace=\"$ns\",op=\"wait_session\"}[2m]))",
     "legendFormat": "平均值"
    }
   ]
  }
 ]
}