{
 "title": "kodo-staging-redis-new",
 "tags": [
  "prometheus",
  "redis",
  "kodo"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(redis_up, cluster)"
   },
   {
    "name": "node",
    "query": "label_values(redis_up{cluster=\"$cluster\"}, node)"
   },
   {
    "name": "name",
    "query": "label_values(redis_up{cluster=\"$cluster\",node=~\"$node\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Basics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_output_bytes_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
     "legendFormat": "{{ node }} {{ name }}"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 * (redis_memory_used_bytes{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}  / redis_memory_max_bytes{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}))"
    }
   ]
  },
  {
   "title": "Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
     "legendFormat": "{{ node }} {{ name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"} / redis_memory_max_bytes{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
     "legendFormat": "{{ node }} {{ name }}"
    }
   ]
  },
  {
   "title": "CPU Usage (Seconds)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(redis_cpu_sys_seconds_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m]))by(node,name)",
     "legendFormat": "{{ node }} {{ name }} sys"
    },
    {
     "expr": "avg(rate(redis_cpu_sys_children_seconds_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m]))by(node,name)",
     "legendFormat": "{{ node }} {{ name }} sys children"
    },
    {
     "expr": "avg(rate(redis_cpu_user_seconds_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m]))by(node,name)",
     "legendFormat": "{{ node }} {{ name }} user"
    },
    {
     "expr": "avg(rate(redis_cpu_user_children_seconds_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m]))by(node,name)",
     "legendFormat": "{{ node }} {{ name }} user children"
    }
   ]
  },
  {
   "title": "Master/Slave",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Master Location",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_instance_info{cluster=\"$cluster\",role=\"master\"}",
       "legendFormat": "{{ node }} {{ name }} {{ redis_mode }} {{ redis_version }}"
      }
     ]
    },
    {
     "title": "Slave Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_connected_slave_lag_seconds{cluster=\"$cluster\"}",
       "legendFormat": "{{slave_ip}}:{{ slave_port }} {{ slave_state }}"
      }
     ]
    },
    {
     "title": "Slave Location",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_slave_info{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }} master: {{ master_host }}:{{ master_port }} read_only: {{ read_only }}"
      }
     ]
    },
    {
     "title": "Connected Slaves",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_connected_slaves{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}>0",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Enabled",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_cluster_enabled{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "Cluster State",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_cluster_state{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "Cluster Known Nodes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_cluster_known_nodes{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "Cluster Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_cluster_size{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "Cluster Current Epoch",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_cluster_current_epoch{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "Cluster My Epoch",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_cluster_my_epoch{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "Cluster Slots Assigned",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_cluster_slots_assigned{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "Cluster Slots OK",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_cluster_slots_ok{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "Cluster Slots Fail",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_cluster_slots_fail{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "Cluster Slots Pfail",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_cluster_slots_pfail{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster Messages Received per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_cluster_messages_received_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "Cluster Messages Sent per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_cluster_messages_sent_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "Cluster Messages Received Ping/Pong per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_cluster_stats_messages_ping_received{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} ping"
      },
      {
       "expr": "rate(redis_cluster_stats_messages_pong_received{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} pong"
      }
     ]
    },
    {
     "title": "Cluster Messages Sent Ping/Pong per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_cluster_stats_messages_ping_sent{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} ping"
      },
      {
       "expr": "rate(redis_cluster_stats_messages_pong_sent{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} pong"
      }
     ]
    },
    {
     "title": "Cluster Messages Received Fail per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_cluster_stats_messages_fail_received{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} auth_ack"
      }
     ]
    },
    {
     "title": "Cluster Messages Sent Fail per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_cluster_stats_messages_fail_sent{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} auth_ack"
      }
     ]
    },
    {
     "title": "Cluster Messages Received Auth/Meet/Update per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_cluster_stats_messages_auth_ack_received{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} auth_ack"
      },
      {
       "expr": "rate(redis_cluster_stats_messages_auth_req_received{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} auth_req"
      },
      {
       "expr": "rate(redis_cluster_stats_messages_meet_received{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} meet"
      },
      {
       "expr": "rate(redis_cluster_stats_messages_update_received{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} update"
      }
     ]
    },
    {
     "title": "Cluster Messages Sent Auth/Meet/Update per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_cluster_stats_messages_auth_ack_sent{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} auth_ack"
      },
      {
       "expr": "rate(redis_cluster_stats_messages_auth_req_sent{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} auth_req"
      },
      {
       "expr": "rate(redis_cluster_stats_messages_meet_sent{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} meet"
      },
      {
       "expr": "rate(redis_cluster_stats_messages_update_sent{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} update"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Time Spent by Command / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(redis_commands_duration_seconds_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[1m])) by (cmd)\n  /\nsum(irate(redis_commands_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[1m])) by (cmd)\n",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Total Time Spent by Command / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(redis_commands_duration_seconds_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[1m])) by (cmd) != 0",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Hits Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "irate(redis_keyspace_hits_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])/\n(irate(redis_keyspace_hits_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])+irate(redis_keyspace_misses_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m]))",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "Hits / Misses per Sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(redis_keyspace_hits_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} hits"
      },
      {
       "expr": "irate(redis_keyspace_misses_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])",
       "legendFormat": "{{ node }} {{ name }} misses"
      }
     ]
    },
    {
     "title": "Slow Log of The Past Hour",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(redis_slowlog_last_id{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[1h])",
       "legendFormat": "{{node}} {{name}}"
      }
     ]
    },
    {
     "title": "Slow Log Length",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_slowlog_length{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{node}} {{name}}"
      }
     ]
    },
    {
     "title": "Total Commands / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_commands_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"} [1m])) by (cmd)",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Connected/Blocked Clients",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_connected_clients{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }} connected"
      },
      {
       "expr": "redis_blocked_clients{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }} blocked"
      }
     ]
    }
   ]
  },
  {
   "title": "Keys",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Expired Keys",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_expired_keys_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])) by (node, name)",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "Evicted Keys",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_evicted_keys_total{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}[5m])) by (node, name)",
       "legendFormat": "{{ node }} {{name}}"
      }
     ]
    },
    {
     "title": "Total Items per DB",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (redis_db_keys{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}) by (db, node, name)",
       "legendFormat": "{{ node }} {{ name }} {{ db }}"
      }
     ]
    },
    {
     "title": "Expiring vs Not-Expiring Keys",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (redis_db_keys{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}) by (node, name) - sum (redis_db_keys_expiring{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}) by (node, name)",
       "legendFormat": "{{ node }} {{ name }} not expiring"
      },
      {
       "expr": "sum (redis_db_keys_expiring{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}) by (node, name)",
       "legendFormat": "{{ node }} {{ name }} expiring"
      }
     ]
    }
   ]
  },
  {
   "title": "AOF",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "AOF Enabled",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_aof_enabled{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "AOF Base Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "redis_aof_base_size_bytes{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "AOF Delayed Fsync",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_aof_delayed_fsync{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "AOF Buffer Length",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "redis_aof_buffer_length{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "AOF Last Cow Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "redis_aof_last_cow_size_bytes{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "AOF Last Rewrite Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_aof_last_rewrite_duration_sec{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}>-1",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "AOF Last BGRewrite Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_aof_last_bgrewrite_status{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "AOF Last Write Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_aof_last_write_status{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "RDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "RDB Last BGSave Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_rdb_last_bgsave_status{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "RDB Last BGSave Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_rdb_last_bgsave_duration_sec{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "RDB Last Cow Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "redis_rdb_last_cow_size_bytes{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "RDB Last Save Timestamp",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "time() - redis_rdb_last_save_timestamp_seconds{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    },
    {
     "title": "RDB Changes Since Last Save",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "redis_rdb_changes_since_last_save{cluster=\"$cluster\",node=~\"$node\",name=~\"$name\"}",
       "legendFormat": "{{ node }} {{ name }}"
      }
     ]
    }
   ]
  }
 ]
}