{
 "title": "shenmengye-mongos",
 "tags": [
  "kodo",
  "mongodb",
  "mongos"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "idc", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(mongodb_op_counters_total{service=~\".*mongos.*\"},namespace)"
   },
   {
    "name": "pod",
    "query": "label_values(mongodb_op_counters_total{service=~\".*mongos.*\", namespace=\"$namespace\"},pod)"
   },
   {
    "name": "shard",
    "query": "label_values(mongodb_mongos_sc_stats_in_use_preshard{namespace=\"$namespace\"}, set)"
   },
   {
    "name": "pool",
    "query": "label_values(mongodb_connpoolstats_c_in_use_in_pool{namespace=\"$namespace\"}, pool)"
   },
   {
    "name": "fuzzy_pool",
    "query": "^NetworkInterfaceASIO-AP.*,^NetworkInterfaceASIO-TaskE.*,NetworkInterfaceASIO-ShardRegistry,global"
   },
   {
    "name": "assert_type",
    "query": "label_values(mongodb_asserts_total{namespace=\"$namespace\"}, type)"
   },
   {
    "name": "ops_type",
    "query": "label_values(mongodb_op_counters_total{namespace=\"$namespace\"}, type)"
   },
   {
    "name": "db",
    "query": "label_values(mongodb_mongos_db_data_size_bytes{namespace=\"$namespace\"},db)"
   }
  ]
 },
 "panels": [
  { "title": "shard连接池", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "传统shard连接池",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongos_sc_stats_in_use_in_pool{pool=\"global\",pod=\"$pod\"}",
     "legendFormat": "InUse"
    },
    {
     "expr": "mongodb_mongos_sc_stats_available_in_pool{pool=\"global\",pod=\"$pod\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "rate(mongodb_mongos_sc_stats_created_in_pool_total{pool=\"global\",pod=\"$pod\"}[1m])",
     "legendFormat": "Created"
    }
   ]
  },
  {
   "title": "use(shard纬度)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_mongos_sc_stats_in_use_preshard{pool=\"global\",set=~\".*shard.*|other\",pod=\"$pod\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "available(shard纬度)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_mongos_sc_stats_available_preshard{pool=\"global\",set=~\".*shard.*|other\",pod=\"$pod\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "create(shard纬度)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mongodb_mongos_sc_stats_created_preshard_total{pool=\"global\",set=~\".*shard.*|other\",pod=\"$pod\"}[1m])) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  { "title": "Route Refreshing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "路由",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mongodb_mongos_ccache_count_failed_refreshes{pod=\"$pod\"}[1m])",
     "legendFormat": "刷新失败次数"
    },
    {
     "expr": "increase(mongodb_mongos_ccache_count_stale_config_errors{pod=\"$pod\"}[1m])",
     "legendFormat": "路由过期次数"
    },
    {
     "expr": "increase(mongodb_mongos_ccache_count_full_refreshes_started{pod=\"$pod\"}[1m])",
     "legendFormat": "full refresh的次数"
    },
    {
     "expr": "increase(mongodb_mongos_ccache_count_incremental_refreshes_started{pod=\"$pod\"}[1m])",
     "legendFormat": "refresh的次数"
    },
    {
     "expr": "increase(mongodb_mongos_ccache_count_full_refreshes_started{pod=\"$pod\"}[1m])",
     "legendFormat": "目前正在full refresh的个数"
    },
    {
     "expr": "mongodb_mongos_ccache_num_active_full_refreshes{pod=\"$pod\"}",
     "legendFormat": "目前正在full refresh的个数"
    },
    {
     "expr": "mongodb_mongos_ccache_num_active_incremental_refreshes{pod=\"$pod\"}",
     "legendFormat": "目前正在refresh的个数"
    }
   ]
  },
  {
   "title": "刷新路由耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(mongodb_mongos_ccache_total_refresh_wait_time_micros{pod=\"$pod\"}[1m]) / 1000",
     "legendFormat": "刷新耗时"
    }
   ]
  },
  { "title": "连接池", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "TP_Find_连接池",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_connpoolstats_c_in_use_in_pool{pod=\"$pod\", pool=~\"^NetworkInterfaceASIO-TaskExecutorPool.*\"})",
     "legendFormat": "InUse"
    },
    {
     "expr": "sum(mongodb_connpoolstats_c_available_in_pool{pod=\"$pod\", pool=~\"^NetworkInterfaceASIO-TaskExecutorPool.*\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(mongodb_connpoolstats_c_refreshing_in_pool{pod=\"$pod\", pool=~\"^NetworkInterfaceASIO-TaskExecutorPool.*\"})",
     "legendFormat": "Refreshing"
    },
    {
     "expr": "sum(mongodb_connpoolstats_c_req_queue_limit_in_pool{pod=\"$pod\", pool=~\"^NetworkInterfaceASIO-TaskExecutorPool.*\"})",
     "legendFormat": "ReqQueue"
    }
   ]
  },
  {
   "title": "Pool Info(根据pool来进行调整)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_connpoolstats_c_in_use_in_pool{pod=\"$pod\", pool=\"$pool\"})",
     "legendFormat": "InUse"
    },
    {
     "expr": "sum(mongodb_connpoolstats_c_available_in_pool{pod=\"$pod\", pool=\"$pool\"})",
     "legendFormat": "Available"
    },
    {
     "expr": "sum(mongodb_connpoolstats_c_refreshing_in_pool{pod=\"$pod\", pool=\"$pool\"})",
     "legendFormat": "Refreshing"
    },
    {
     "expr": "sum(mongodb_connpoolstats_c_req_queue_limit_in_pool{pod=\"$pod\", pool=\"$pool\"})",
     "legendFormat": "ReqQueue"
    }
   ]
  },
  {
   "title": "use(shard纬度)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_connpoolstats_c_in_use_preshard{pod=\"$pod\",pool=~\"$fuzzy_pool\",set=~\".*shard.*|other\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "available(shard纬度)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_connpoolstats_c_available_preshard{pod=\"$pod\",pool=~\"$fuzzy_pool\",set=~\".*shard.*|other\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "waitReq(shard纬度)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_connpoolstats_c_req_queue_limit_preshard{pod=\"$pod\",pool=~\"$fuzzy_pool\",set=~\".*shard.*|other\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "refreshing(shard纬度)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mongodb_connpoolstats_c_refreshing_preshard{pod=\"$pod\",pool=~\"$fuzzy_pool\",set=~\".*_shard.*|other\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  { "title": "异常统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "mongos的限制",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"limitForAsioReqQ\"}[1m])",
     "legendFormat": "触发find请求队列满"
    },
    {
     "expr": "rate(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"limitForLegacy\"}[1m])",
     "legendFormat": "触发传统连接池满"
    },
    {
     "expr": "rate(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"limitForRefresh\"}[1m])",
     "legendFormat": "触发getshardhost限制"
    }
   ]
  },
  {
   "title": "ap/tp ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"readap\"}[1m])",
     "legendFormat": "ap"
    },
    {
     "expr": "rate(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"readtp\"}[1m])",
     "legendFormat": "tp"
    },
    {
     "expr": "rate(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"error_ap_exec\"}[1m])",
     "legendFormat": "ap error"
    }
   ]
  },
  {
   "title": "mongos的慢日志统计",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"r_s_l\"}[1m])",
     "legendFormat": "read_slow_log"
    },
    {
     "expr": "increase(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"r_a_s_l\"}[1m])",
     "legendFormat": "read_ap_slow_log"
    },
    {
     "expr": "rate(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"f_s_l\"}[1m])",
     "legendFormat": "fam_slow_log"
    },
    {
     "expr": "rate(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"w_s_l\"}[1m])",
     "legendFormat": "write_slow_log"
    },
    {
     "expr": "rate(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"c_s_l\"}[1m])",
     "legendFormat": "cmd_slow_log"
    },
    {
     "expr": "rate(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"r_d_s_l\"}[1m])",
     "legendFormat": "read_d_slow_log"
    },
    {
     "expr": "rate(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"r_a_d_s_l\"}[1m])",
     "legendFormat": "read_ap_d_slow_log"
    },
    {
     "expr": "rate(mongodb_mongos_ap_counters_total{pod=\"$pod\", type=\"r_un_s_l\"}[1m])",
     "legendFormat": "read_un_slow_log"
    }
   ]
  },
  {
   "title": "mongos refresh limiter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_connpoolstats_c_refresh_limit{pod=\"$pod\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Mongos Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Mongo Assert QPS For Cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_asserts_total{service=~\".*mongos\"}[2m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mongo Operations QPS For Cluster",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_op_counters_total{service=~\".*mongos\"}[2m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mongo Assert QPS For Single Mongos",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_asserts_total{service=~\".*mongos\",type=\"$assert_type\"}[2m])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Mongo Operations QPS For Single Mongos",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_op_counters_total{service=~\".*mongos\",type=\"$ops_type\"}[2m])) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Mongo Wait Write Ack For Cluster",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongos_metrics_get_last_error_wtime_num_total{service=~\".*mongos.*\"}[2m])) ",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(rate(mongodb_mongod_metrics_get_last_error_wtimeouts_total{service=~\".*shard.*\"}[2m])) ",
     "legendFormat": "Timeout"
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 97 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "mongodb_instance_uptime_seconds{pod=\"$pod\",service=~\".*mongos\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Mongodb Version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 97 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "mongodb_version_info{pod=\"$pod\", service=~\".*mongos\", namespace=\"$namespace\"}",
     "legendFormat": "version:{{mongodb}}"
    }
   ]
  },
  {
   "title": "Shard Chunk Info",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongos_sharding_shard_chunks_total{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Shard Num",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 100 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mongodb_mongos_sharding_shards_total{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}"
    }
   ]
  },
  { "title": "Ops Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Mongo Operations QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_op_counters_total{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mongo Assert QPM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(mongodb_asserts_total{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "mongos等待write ack的个数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongos_metrics_get_last_error_wtime_num_total{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}[2m])",
     "legendFormat": "{{node}}-Waiting"
    }
   ]
  },
  {
   "title": "cursor 超时个数",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongos_metrics_cursor_timed_out_total{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}[2m])",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "cursor open status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongos_metrics_cursor_open{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Last 10m Changelog Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongos_sharding_changelog_10min_total{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}",
     "legendFormat": "{{event}}"
    }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "mongos session统计",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_connections{pod=\"$pod\", service=~\".*mongos\", state!=\"available\",namespace=\"$namespace\"}",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_connections_metrics_created_total{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}[2m])",
     "legendFormat": "created"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 130 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (name,service,type) (irate(metric_process_status{pod=\"$pod\",type=~\"utime|stime\",name=~\".*mongos.*\"}[1m])) / 1000 ",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Mongos Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 130 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "metric_process_status{node=\"$node\",type=\"mem\",name=~\".*mongos.*\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "文件句柄",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metric_process_status{node=\"$node\",type=\"fd_current\",name=~\".*mongos\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "连接池的使用状况",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_connpoolstats_connection_sync{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}",
     "legendFormat": "当前使用dbclient的个数"
    },
    {
     "expr": "mongodb_connpoolstats_connections_available{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}",
     "legendFormat": "available"
    },
    {
     "expr": "mongodb_connpoolstats_connections_in_use{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}",
     "legendFormat": "use"
    },
    {
     "expr": "mongodb_connpoolstats_connections_scoped_sync{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}",
     "legendFormat": "临时的dbclient"
    }
   ]
  },
  {
   "title": "DB/Coll的信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shard-DB-DataSize",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 146 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongos_db_data_size_bytes{pod=\"$pod\", service=~\".*mongos\", db=\"$db\",namespace=\"$namespace\"}",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "Shard-DB-IndexSize",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 146 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongos_db_index_size_bytes{pod=\"$pod\", service=~\".*mongos\", db=\"$db\",namespace=\"$namespace\"}",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "Shard-DB-Indexs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 16, "y": 146 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongos_db_indexes_total{pod=\"$pod\", service=~\".*mongos\", db=\"$db\",namespace=\"$namespace\"}",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "Global DB Num Status",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 153 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongos_sharding_databases_total{pod=\"$pod\", service=~\".*mongos\",namespace=\"$namespace\"}",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Global DB Collection Num ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 153 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongos_db_collections_total{pod=\"$pod\", service=~\".*mongos\", db=\"$db\",namespace=\"$namespace\"}",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "Shard-DB-Objs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 153 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "mongodb_mongos_db_objects_total{pod=\"$pod\", service=~\".*mongos\", db=\"$db\",namespace=\"$namespace\"}",
       "legendFormat": "{{shard}}"
      }
     ]
    }
   ]
  }
 ]
}